name: stability_sdk
description: An implementation of Stability AI SDK in Dart. Stability AI is a solution studio dedicated to innovating ideas.
version: 0.1.0
homepage: https://github.com/joshuadeguzman/stability-sdk-dart

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.1.0
  grpc: ^3.1.0
  fixnum: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: